# Generated by Django 4.2.6 on 2023-11-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha',
        ),
    ]
