# Generated by Django 4.2.6 on 2023-11-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_blog', '0002_remove_articulo_cuerpo_remove_articulo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cuerpo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
