# Generated by Django 4.2.6 on 2023-11-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_blog', '0003_articulo_cuerpo_articulo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_articulos'),
        ),
    ]
