# Generated by Django 4.2.6 on 2023-11-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_blog', '0006_delete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('articulo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos_blog.articulo')),
            ],
        ),
    ]
