# Generated by Django 4.2.6 on 2023-11-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_blog', '0007_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
