# Generated by Django 4.2.6 on 2023-11-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_blog', '0014_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
