# Generated by Django 4.2.6 on 2023-11-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('año_publicacion', models.IntegerField(blank=True, null=True)),
                ('sinopsis', models.TextField(null=True)),
                ('reseña', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('año_publicacion', models.IntegerField(blank=True, null=True)),
                ('sinopsis', models.TextField(null=True)),
                ('reseña', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilosofiaYReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('año_publicacion', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('reseña', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfantilYJuvenil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('año_publicacion', models.IntegerField(blank=True, null=True)),
                ('sinopsis', models.TextField(null=True)),
                ('reseña', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('año_publicacion', models.IntegerField(blank=True, null=True)),
                ('sinopsis', models.TextField(null=True)),
                ('reseña', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
