# Generated by Django 4.2.6 on 2023-11-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias_libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biografia',
            name='reseña',
        ),
        migrations.RemoveField(
            model_name='ficcion',
            name='reseña',
        ),
        migrations.RemoveField(
            model_name='filosofiayreligion',
            name='reseña',
        ),
        migrations.RemoveField(
            model_name='infantilyjuvenil',
            name='reseña',
        ),
        migrations.RemoveField(
            model_name='poesia',
            name='reseña',
        ),
    ]
